# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
