# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitty', '0002_post_body_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle_text',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
