# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitty', '0003_post_subtitle_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_text',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
