# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitty', '0004_post_url_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='url_text',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
