# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitty', '0005_auto_20170726_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_intro_text', models.TextField()),
            ],
        ),
    ]
