# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 11:59
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitty', '0007_auto_20170729_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='self_intro_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
